CREATE CONSTRAINT IF NOT EXISTS FOR (u:Usuario) REQUIRE u.id IS UNIQUE; 
CREATE CONSTRAINT IF NOT EXISTS FOR (f:Filme) REQUIRE f.id IS UNIQUE; 
CREATE CONSTRAINT IF NOT EXISTS FOR (g:Genero) REQUIRE g.nome IS UNIQUE; 
CREATE INDEX IF NOT EXISTS FOR (f:Filme) ON (f.titulo); 
